server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location /_next/static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(?:avif|gif|jpg|jpeg|pdf|png|svg|ttf|webp|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    location ~* \.glb$ {
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }
}
